[workspace]
authors = ["Wesley Scholl <128409641+wesleyscholl@users.noreply.github.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "mojo"
platforms = ["osx-arm64"]
version = "1.0.0"

[tasks]

[dependencies]
mojo = ">=0.25.7.0.dev2025102305,<0.26"
modular = ">=25.7.0.dev2025102305,<26"
pip = ">=25.2,<26"
