[build-system]
requires = ["setuptools>=61.0", "wheel", "cython>=0.29", "numpy>=1.25"]
build-backend = "setuptools.build_meta"

[project]
name = "vectro"
version = "0.2.0"
description = "Ultra-high-performance LLM embedding compressor with Mojo and Cython backends"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "Wesley Scholl", email = "wesley.scholl@example.com"}
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
keywords = ["embeddings", "quantization", "compression", "llm", "mojo", "performance"]
requires-python = ">=3.8"
dependencies = [
    "numpy>=1.25",
    "cython>=0.29",
    "click>=8.0",
    "matplotlib>=3.5",
    "scikit-learn>=1.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-cov",
]
bench = [
    "rich>=13.0",
    "tqdm>=4.0",
]
mojo = [
    # Mojo SDK is required for building from source with Mojo backend
    # Install from: https://www.modular.com/mojo
]

[project.urls]
Homepage = "https://github.com/yourusername/vectro"
Documentation = "https://github.com/yourusername/vectro#readme"
Repository = "https://github.com/yourusername/vectro"
Issues = "https://github.com/yourusername/vectro/issues"

[project.scripts]
vectro = "python.cli:main"

[tool.setuptools]
packages = ["vectro", "python"]
package-dir = {"" = "."}

[tool.setuptools.package-data]
vectro = ["*.pyx", "*.pxi"]
"*" = ["vectro_quantizer*", "src/*.mojo"]

[tool.cython]
language_level = 3