from typing import Dict, Iterable, List, Optional, Sequence, Union

import numpy as np

TextLike = Union[str, Sequence[str]]

class BaseEmbeddingProvider:
    provider_name: str
    model: str
    batch_size: int
    cache_dir: Optional[str]
    normalize: bool
    dimension: Optional[int]

    def __init__(
        self,
        model: str,
        batch_size: int = ...,
        cache_dir: Optional[str] = ...,
        normalize: bool = ...,
        dimension: Optional[int] = ...,
    ) -> None: ...
    def _embed_batch(self, texts: List[str]) -> np.ndarray: ...
    def _cache_key(self, text: str) -> str: ...
    def _cache_get(self, keys: List[str]) -> Dict[str, np.ndarray]: ...
    def _cache_put(self, items: Dict[str, np.ndarray]) -> None: ...
    def cache_stats(self) -> Dict[str, int]: ...
    def clear_cache(self) -> None: ...
    def close(self) -> None: ...
    @staticmethod
    def _l2_normalize(mat: np.ndarray) -> np.ndarray: ...
    def _embed_uncached(self, texts: List[str]) -> np.ndarray: ...
    def embed_texts(self, texts: Iterable[str]) -> np.ndarray: ...
    def __call__(self, x: TextLike) -> np.ndarray: ...
    def embed_query(self, text: str) -> List[float]: ...
    def embed_documents(self, texts: List[str]) -> List[List[float]]: ...
    async def aembed_query(self, text: str) -> List[float]: ...
    async def aembed_documents(self, texts: List[str]) -> List[List[float]]: ...
    def _get_query_embedding(self, query: str) -> List[float]: ...
    def _get_text_embedding(self, text: str) -> List[float]: ...
    def _get_text_embeddings(self, texts: List[str]) -> List[List[float]]: ...
    async def _aget_query_embedding(self, query: str) -> List[float]: ...
    async def _aget_text_embedding(self, text: str) -> List[float]: ...
