import numpy as np

_BINARY_NAME: str

def _find_binary() -> str | None: ...

_binary_path: str | None

def is_available() -> bool: ...
def binary_path() -> str: ...
def _write_f32(arr: np.ndarray, path: str) -> None: ...
def _read_f32(path: str, count: int) -> np.ndarray: ...
def _write_i8(arr: np.ndarray, path: str) -> None: ...
def _read_i8(path: str, count: int) -> np.ndarray: ...
def _write_u8(arr: np.ndarray, path: str) -> None: ...
def _read_u8(path: str, count: int) -> np.ndarray: ...
def _run(args: list[str]) -> None: ...
def int8_quantize(vectors: np.ndarray) -> tuple[np.ndarray, np.ndarray]: ...
def int8_reconstruct(q: np.ndarray, scales: np.ndarray, d: int | None = None) -> np.ndarray: ...
def nf4_encode(vectors: np.ndarray) -> tuple[np.ndarray, np.ndarray]: ...
def nf4_decode(packed: np.ndarray, scales: np.ndarray, d: int) -> np.ndarray: ...
def bin_encode(vectors: np.ndarray) -> np.ndarray: ...
def bin_decode(packed: np.ndarray, d: int) -> np.ndarray: ...
