import numpy as np

_HAS_SCIPY: bool

def _cosine_sim_mean(a: np.ndarray, b: np.ndarray) -> float: ...
def _compute_kurtosis(embeddings: np.ndarray) -> float: ...
def _compression_ratio_nf4(d: int) -> float: ...
def _compression_ratio_pq(d: int, code_bytes: int) -> float: ...
def _compression_ratio_binary(d: int) -> float: ...
def _try_nf4(embeddings: np.ndarray, mixed: bool = False) -> dict: ...
def _try_pq(embeddings: np.ndarray, target_code_bytes: int) -> dict: ...
def _try_binary(embeddings: np.ndarray) -> dict: ...
def _try_int8_fallback(embeddings: np.ndarray) -> dict: ...
def auto_quantize(embeddings: np.ndarray, target_cosine: float = 0.97, target_compression: float = 8.0) -> dict: ...
