import numpy as np
from . import _mojo_bridge as _mojo_bridge
from _typeshed import Incomplete

_spec: Incomplete

def quantize_binary(vectors: np.ndarray, normalize: bool = True) -> np.ndarray: ...
def dequantize_binary(packed: np.ndarray, d: int) -> np.ndarray: ...
def hamming_distance_batch(query_packed: np.ndarray, db_packed: np.ndarray) -> np.ndarray: ...
def binary_search(query: np.ndarray, db_packed: np.ndarray, top_k: int = 10, normalize: bool = True) -> tuple[np.ndarray, np.ndarray]: ...
def matryoshka_encode(vectors: np.ndarray, dims: list[int], normalize: bool = True) -> dict: ...
def binary_compression_ratio(d: int) -> float: ...
