import argparse

_VERSION: str

def _cmd_compress(args: argparse.Namespace) -> int: ...
def _cmd_decompress(args: argparse.Namespace) -> int: ...
def _cmd_inspect(args: argparse.Namespace) -> int: ...
def _cmd_upgrade(args: argparse.Namespace) -> int: ...
def _cmd_validate(args: argparse.Namespace) -> int: ...
def _cmd_benchmark(args: argparse.Namespace) -> int: ...
def _cmd_info(args: argparse.Namespace) -> int: ...
def _run_inline_benchmark() -> None: ...
def _build_parser() -> argparse.ArgumentParser: ...
def main(argv: list | None = None) -> None: ...
