import numpy as np
from _typeshed import Incomplete

def _xavier(fan_in: int, fan_out: int, rng: np.random.Generator) -> np.ndarray: ...
def _relu(x: np.ndarray) -> np.ndarray: ...
def _relu_grad(x: np.ndarray) -> np.ndarray: ...
def _cosine_loss_and_grad(recon: np.ndarray, target: np.ndarray) -> tuple[float, np.ndarray]: ...

class Codebook:
    target_dim: Incomplete
    l2_reg: Incomplete
    seed: Incomplete
    _rng: Incomplete
    _d: int
    _hidden: int
    W1e: np.ndarray | None
    W2e: np.ndarray | None
    W1d: np.ndarray | None
    W2d: np.ndarray | None
    _m: dict
    _v: dict
    _t: int
    _code_scale: float
    is_trained: bool
    def __init__(self, target_dim: int = 64, l2_reg: float = 0.0001, seed: int = 42) -> None: ...
    def _encode_float(self, x: np.ndarray) -> np.ndarray: ...
    def _decode_float(self, z: np.ndarray) -> np.ndarray: ...
    def train(self, embeddings: np.ndarray, n_epochs: int = 100, lr: float = 0.01, batch_size: int = 64) -> Codebook: ...
    def encode(self, embeddings: np.ndarray) -> np.ndarray: ...
    def decode(self, codes: np.ndarray) -> np.ndarray: ...
    def mean_cosine(self, original: np.ndarray, reconstructed: np.ndarray) -> float: ...
    def compression_ratio(self) -> float: ...
    def save(self, path: str) -> None: ...
    @classmethod
    def load(cls, path: str) -> Codebook: ...
