import numpy as np

def gpu_available() -> bool: ...
def gpu_device_info() -> dict: ...
def quantize_int8_batch(vectors: np.ndarray) -> tuple[np.ndarray, np.ndarray]: ...
def reconstruct_int8_batch(quantized: np.ndarray, scales: np.ndarray) -> np.ndarray: ...
def batch_cosine_similarity(vectors_a: np.ndarray, vectors_b: np.ndarray) -> np.ndarray: ...
def batch_cosine_int8(quantized: np.ndarray, scales: np.ndarray) -> np.ndarray: ...
def batch_cosine_query(queries: np.ndarray, database: np.ndarray, top_k: int = 10) -> tuple[np.ndarray, np.ndarray]: ...
def batch_topk_int8(db_quantized: np.ndarray, db_scales: np.ndarray, queries: np.ndarray, top_k: int = 10) -> tuple[np.ndarray, np.ndarray]: ...
def pq_encode_gpu(vectors: np.ndarray, codebook, batch_size: int = 4096) -> np.ndarray: ...
def gpu_benchmark(n: int = 10000, d: int = 768) -> dict: ...
