import numpy as np
from _typeshed import Incomplete
from pathlib import Path as Path

def _cosine_dist(a: np.ndarray, b: np.ndarray) -> float: ...
def _l2_dist_sq(a: np.ndarray, b: np.ndarray) -> float: ...
def _heap_push_result(W: list, dist: float, nid: int, ef: int) -> None: ...
def _heap_worst_dist(W: list) -> float: ...

class HNSWIndex:
    M: Incomplete
    M0: Incomplete
    ef_construction: Incomplete
    space: Incomplete
    _ml: Incomplete
    _vectors: list[np.ndarray]
    _neighbors: list[list[list[int]]]
    _levels: list[int]
    _entry_point: int
    _max_level: int
    def __init__(self, M: int = 16, ef_construction: int = 200, space: str = 'cosine') -> None: ...
    def _distance(self, a: np.ndarray, b: np.ndarray) -> float: ...
    def _random_level(self) -> int: ...
    def _normalize(self, v: np.ndarray) -> np.ndarray: ...
    def _search_layer(self, query: np.ndarray, entry_points: list[int], ef: int, layer: int) -> list[tuple[float, int]]: ...
    def _select_neighbors(self, candidates: list[tuple[float, int]], M: int) -> list[int]: ...
    def _insert_one(self, vector: np.ndarray) -> int: ...
    def add(self, vectors: np.ndarray) -> None: ...
    def search(self, query: np.ndarray, k: int = 10, ef: int = 64) -> tuple[np.ndarray, np.ndarray]: ...
    def save(self, path: str) -> None: ...
    @classmethod
    def load(cls, path: str) -> HNSWIndex: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

def build_hnsw_index(vectors: np.ndarray, M: int = 16, ef_construction: int = 200, space: str = 'cosine') -> HNSWIndex: ...
def hnsw_search(index: HNSWIndex, query: np.ndarray, k: int = 10, ef: int = 64) -> tuple[np.ndarray, np.ndarray]: ...
def recall_at_k(index: HNSWIndex, queries: np.ndarray, ground_truth: np.ndarray, k: int = 10, ef: int = 64) -> float: ...
def hnsw_compression_info(d: int, M: int = 16) -> dict: ...
