import numpy as np
from . import _mojo_bridge as _mojo_bridge
from _typeshed import Incomplete
from typing import NamedTuple

class QuantizationResult(NamedTuple):
    quantized: np.ndarray
    scales: np.ndarray
    dims: int
    n: int
    precision_mode: str = ...
    group_size: int = ...

_cython_quant: Incomplete
_squish_quant: Incomplete
_mojo_available: bool
_mojo_binary: str | None

def _quantize_with_squish(embeddings: np.ndarray, group_size: int = 0) -> QuantizationResult: ...
def _dequantize_with_squish(result: QuantizationResult) -> np.ndarray: ...
def quantize_int4(embeddings: np.ndarray, group_size: int = 64) -> tuple[np.ndarray, np.ndarray]: ...
def dequantize_int4(packed: np.ndarray, scales: np.ndarray, group_size: int = 64) -> np.ndarray: ...
def _quantize_vectorized(embeddings: np.ndarray, group_size: int = 0) -> QuantizationResult: ...
def _quantize_with_mojo(embeddings: np.ndarray) -> QuantizationResult: ...
def _reconstruct_with_mojo(result: QuantizationResult) -> np.ndarray: ...
def get_backend_info(): ...
def quantize_embeddings(embeddings: np.ndarray, backend: str = 'auto', precision_mode: str = 'int8', group_size: int = 64) -> QuantizationResult: ...
def reconstruct_embeddings(result: QuantizationResult, backend: str = 'auto') -> np.ndarray: ...
def mean_cosine_similarity(a: np.ndarray, b: np.ndarray) -> float: ...
