from _typeshed import Incomplete
from pathlib import Path
from typing import Any

_CURRENT_FORMAT_VERSION: int
_STORAGE_FORMAT_NAME: str
_V1_DEFAULTS: Incomplete

def inspect_artifact(path: str | Path) -> dict[str, Any]: ...
def validate_artifact(path: str | Path) -> dict[str, Any]: ...
def upgrade_artifact(src: str | Path, dst: str | Path, *, dry_run: bool = False) -> dict[str, Any]: ...
def _cmd_inspect(args: list) -> int: ...
def _cmd_upgrade(args: list) -> int: ...
def _cmd_validate(args: list) -> int: ...
def _main(argv: list | None = None) -> None: ...
