import numpy as np
from . import _mojo_bridge as _mojo_bridge
from _typeshed import Incomplete

_spec: Incomplete
NF4_LEVELS: np.ndarray
_NF4_THRESHOLDS: np.ndarray

def quantize_nf4(vectors: np.ndarray) -> tuple[np.ndarray, np.ndarray]: ...
def dequantize_nf4(packed: np.ndarray, scales: np.ndarray, d: int) -> np.ndarray: ...
def select_outlier_dims(training_data: np.ndarray, k: int = 16) -> np.ndarray: ...
def quantize_mixed(vectors: np.ndarray, outlier_dims: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]: ...
def dequantize_mixed(fp16_vals: np.ndarray, nf4_packed: np.ndarray, nf4_scales: np.ndarray, outlier_dims: np.ndarray, d: int) -> np.ndarray: ...
def nf4_cosine_sim(original: np.ndarray, reconstructed: np.ndarray) -> float: ...
def compression_ratio(d: int, k_outliers: int = 0) -> float: ...
