import numpy as np
from _typeshed import Incomplete

def _check_sklearn() -> None: ...
def _fit_pq_codebook(data: np.ndarray, n_subspaces: int, n_centroids: int, seed: int = 0) -> list[np.ndarray]: ...
def _pq_encode_one(data: np.ndarray, codebooks: list[np.ndarray], n_subspaces: int) -> np.ndarray: ...
def _pq_decode_one(codes: np.ndarray, codebooks: list[np.ndarray], n_subspaces: int, d_orig: int) -> np.ndarray: ...

class ResidualQuantizer:
    n_passes: Incomplete
    n_subspaces: Incomplete
    n_centroids: Incomplete
    seed: Incomplete
    _codebooks: list[list[np.ndarray]]
    _d_orig: int
    is_trained: bool
    def __init__(self, n_passes: int = 3, n_subspaces: int = 8, n_centroids: int = 64, seed: int = 0) -> None: ...
    def train(self, data: np.ndarray) -> ResidualQuantizer: ...
    def encode(self, vectors: np.ndarray) -> list[np.ndarray]: ...
    def decode(self, codes_list: list[np.ndarray]) -> np.ndarray: ...
    def mean_cosine(self, original: np.ndarray, reconstructed: np.ndarray) -> float: ...
    def compression_ratio(self) -> float: ...
