import numpy as np
from .batch_api import BatchCompressionAnalyzer as BatchCompressionAnalyzer, BatchQuantizationResult as BatchQuantizationResult, VectroBatchProcessor as VectroBatchProcessor, benchmark_batch_compression as benchmark_batch_compression, quantize_embeddings_batch as quantize_embeddings_batch
from .interface import QuantizationResult as QuantizationResult, get_backend_info as get_backend_info, mean_cosine_similarity as mean_cosine_similarity, quantize_embeddings as quantize_embeddings, reconstruct_embeddings as reconstruct_embeddings
from .profiles_api import CompressionOptimizer as CompressionOptimizer, CompressionProfile as CompressionProfile, CompressionStrategy as CompressionStrategy, ProfileComparison as ProfileComparison, ProfileManager as ProfileManager, create_custom_profile as create_custom_profile, get_compression_profile as get_compression_profile
from .quality_api import QualityBenchmark as QualityBenchmark, QualityMetrics as QualityMetrics, QualityReport as QualityReport, VectroQualityAnalyzer as VectroQualityAnalyzer, evaluate_quantization_quality as evaluate_quantization_quality, generate_quality_report as generate_quality_report
from _typeshed import Incomplete
from pathlib import Path as Path
from typing import Any

__version__: str
__author__: str
__license__: str
__description__: str
_STORAGE_FORMAT_VERSION: int
_STORAGE_FORMAT_NAME: str

class Vectro:
    backend: Incomplete
    default_profile: Incomplete
    enable_batch_optimization: Incomplete
    batch_processor: Incomplete
    quality_analyzer: Incomplete
    _performance_cache: Incomplete
    def __init__(self, backend: str = 'auto', profile: str = 'balanced', enable_batch_optimization: bool = True) -> None: ...
    def compress(self, vectors: np.ndarray | list[np.ndarray], profile: str | None = None, precision_mode: str | None = None, return_quality_metrics: bool = False) -> QuantizationResult | BatchQuantizationResult | tuple[Any, QualityMetrics]: ...
    def decompress(self, result: QuantizationResult | BatchQuantizationResult) -> np.ndarray: ...
    def analyze_quality(self, original: np.ndarray, compressed_result: QuantizationResult | BatchQuantizationResult) -> QualityMetrics: ...
    def benchmark_performance(self, vector_dims: list[int] = None, batch_sizes: list[int] = None, profiles: list[str] = None, num_trials: int = 3) -> dict[str, Any]: ...
    def optimize_profile(self, sample_vectors: np.ndarray, target_similarity: float = 0.995, target_compression: float = 3.0) -> CompressionProfile: ...
    def compare_profiles(self, vectors: np.ndarray, profile_names: list[str] = None) -> str: ...
    def save_compressed(self, result: QuantizationResult | BatchQuantizationResult, filepath: str, metadata: dict[str, Any] | None = None): ...
    def load_compressed(self, filepath: str) -> QuantizationResult | BatchQuantizationResult: ...
    def _compress_single_batch(self, vectors: np.ndarray, profile: str, precision_mode: str = 'int8') -> BatchQuantizationResult: ...
    def _compress_individually(self, vectors: np.ndarray, profile: str, precision_mode: str = 'int8') -> BatchQuantizationResult: ...
    @property
    def available_profiles(self) -> list[str]: ...
    @property
    def backend_info(self) -> dict[str, Any]: ...

def compress_vectors(vectors: np.ndarray | list[np.ndarray], profile: str = 'balanced', backend: str = 'auto') -> QuantizationResult | BatchQuantizationResult: ...
def decompress_vectors(result: QuantizationResult | BatchQuantizationResult) -> np.ndarray: ...
def analyze_compression_quality(original: np.ndarray, result: QuantizationResult | BatchQuantizationResult) -> QualityMetrics: ...
def generate_compression_report(original: np.ndarray, result: QuantizationResult | BatchQuantizationResult) -> str: ...
def set_default_backend(backend: str): ...
def get_version_info() -> dict[str, str]: ...
